alias sc='sc-im'
alias b='book.sh'
alias grep='grep --color'
alias srd='sr duckduckgo'
alias ls='ls --color=auto'
alias tx='tmux a || tmux new -s alazarte'
alias t='todo.sh'
alias cs='xclip -selection clipboard'
alias ix="curl -F 'f:1=<-' -F 'read:1=2' ix.io"
alias webget='wget --mirror --convert-links --adjust-extension --page-requisites --no-parent'
alias pihole='docker exec pihole pihole'
alias tf='terraform'
alias ng='docker run --rm -ti -v $PWD:/ng ng-cli:latest'
