syntax enable

" Vundle config {{{

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'christoomey/vim-tmux-navigator'
call vundle#end()
filetype plugin indent on

" }}}

" Setters {{{

set softtabstop=4
set shiftwidth=4
set expandtab

set wildmenu
"set wildmode=list:longest,full

set relativenumber
set number

" start search while typing
set incsearch
set hlsearch

" show trailing and not wanted blank characters
set list
set listchars=tab:>-,nbsp:_,trail:.

" hidden buffer to hold changes in current file with changes
set hidden

set clipboard=unnamedplus

" no autochdir
set tags=./tags;

" recursive finding path
set path+=**

" }}}

" Explorer Configuration {{{

" remove banner in explore
let g:netrw_banner = 0
let g:netrw_liststyle = 3

" }}}

" Mapping {{{

" Faster scrolling
nmap <C-d> 5<C-e>
nmap <C-u> 5<C-y>

" Clipboard
"" TODO fix this
map ,c :w !xclip -selection clipboard<CR><CR>
map ,C :r!xclip -o<CR>

" TODO replace with vim's find
" nmap <C-P> :FZF<CR>

map ,s :setlocal spell! spelllang=en_us<cr>
map ,v <esc>:e ~/.vim/vimrc<cr>
map ,l <esc>:so ~/.vim/vimrc<cr>

"}}}

" Folding {{{

set foldenable
set foldlevel=0
set foldcolumn=0
set foldmethod=marker           " detect triple-{ style fold markers

" }}}

" Highlight {{{

colorscheme simple

" }}}

" {{{ Restore cursor

function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END

" }}}

" Commands {{{

command! MakeTags ! ctags -R .
command! GF ! go fmt ./...
command! GR ! go run %
map ,f <esc>:! go fmt ./...<cr>
map ,r <esc>:! go run %<cr>

" }}}
