" Vundle config {{{

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-sleuth'
Plugin 'tpope/vim-commentary'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'vim-scripts/AfterColors.vim'
call vundle#end()
filetype plugin indent on

" }}}
" Letters {{{

let g:netrw_keepdir=0
let mapleader = ","

" }}}
" Setters {{{

set showcmd
set relativenumber
set number

" start search while typing
set hlsearch

" hidden buffer to hold changes in current file with changes
set hidden

" show trailing chars
set list

set tags=tags;

" . current directory for file
" current directory ...
" ** recursive
set path=.,,**

" TODO choose a better termwinkey
set termwinkey=<C-A>

set showcmd

set scroll=10

set background=dark

" }}}
" Explorer Configuration {{{

" remove banner in explore
let g:netrw_banner = 0
let g:netrw_liststyle = 3

" }}}
" Mapping {{{

" Faster scrolling

" Clipboard
"" TODO fix this
map <leader>c :w !xclip -selection clipboard<CR><CR>
map <leader>C :r!xclip -o<CR>

" TODO replace with vim's find
" nmap <C-P> :FZF<CR>

map <leader>s :setlocal spell! spelllang=en_us<cr>
map <leader>v <esc>:e ~/.vim/vimrc<cr>
map <leader>l <esc>:so ~/.vim/vimrc<cr>
map <leader>h <esc>:lcd %:h<cr>
map <leader>jq <esc>:%!jq<cr>

cnoremap w!! w !sudo tee % >/dev/null

map j gj
map k gk

"}}}
" Folding {{{

set foldenable
set foldlevel=0
set foldcolumn=0
set foldmethod=marker           " detect triple-{ style fold markers

" }}}
" Colorscheme {{{

colorscheme default

" }}}
" {{{ Restore cursor

function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END

" }}}
" Commands {{{

command! MakeTags ! ctags -R .
command! GF ! go fmt ./...
command! GR ! go run %:p

" }}}
" Status Line {{{

set statusline=%y\ %f\ %m\ %r\ %w\ %q\ %=%l:%c

" }}}
