alias sc='sc-im'
alias b='book.sh'
alias grep='grep --color'
alias srd='sr duckduckgo'
alias ls='ls --color=auto'
alias tx='tmux a || tmux new -s alazarte'
alias t='todo.sh'
alias cs='xclip -selection clipboard'
alias ix="curl -F 'f:1=<-' -F 'read:1=2' ix.io"
alias webget='wget --mirror --convert-links --adjust-extension --page-requisites --no-parent'
alias pihole='docker exec pihole pihole'
alias tf='terraform'
alias noise='play -q -c 2 --null synth brownnoise band -n 2500 4000 tremolo 20 .1 reverb 50'
alias zt='zerotier-start'
alias wtr='curl wttr.in/cba'
alias g="git"
